/**
 * Auto-generated by scripts/generate-icons.mjs — do not edit by hand.
 * Add a .svg next to this file, then run `npm run icons:generate` (or `npm run dev` / `npm run build`).
 */

export { default as IArrowDown } from "./arrow-down.svg?react";
export { default as IArrowRight } from "./arrow-right.svg?react";
export { default as IDot } from "./dot.svg?react";
export { default as IStar } from "./star.svg?react";
