/**
 * Scans src/assets/icons/*.svg and writes index.ts with SVGR exports (I + PascalCase).
 * Run automatically via predev / prebuild, or: npm run icons:generate
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.join(__dirname, "../src/assets/icons");

/** Filenames to skip (template / non-UI assets in the same folder). */
const IGNORE = new Set(["vite.svg", "typescript.svg"]);

function toExportName(filename) {
  const base = filename.replace(/\.svg$/i, "");
  const pascal = base
    .split(/[-_]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join("");
  return `I${pascal}`;
}

const files = fs
  .readdirSync(iconsDir)
  .filter((f) => f.endsWith(".svg") && !IGNORE.has(f))
  .sort((a, b) => a.localeCompare(b));

const header = `/**
 * Auto-generated by scripts/generate-icons.mjs — do not edit by hand.
 * Add a .svg next to this file, then run \`npm run icons:generate\` (or \`npm run dev\` / \`npm run build\`).
 */
`;

const lines = [header];
for (const f of files) {
  const name = toExportName(f);
  lines.push(`export { default as ${name} } from "./${f}?react";`);
}
lines.push("");

fs.writeFileSync(path.join(iconsDir, "index.ts"), lines.join("\n"), "utf8");
console.log(`generated ${files.length} icon exports → src/assets/icons/index.ts`);
